STATE_START = 0
STATE_SELECT = 1
STATE_CH_HOUR = 2
STATE_CH_MINUTE = 3
STATE_CH_MODE = 4
STATE_BEGIN = 5
STATE_BLACK_MOVE = 6
STATE_WHITE_MOVE = 7
STATE_BLACK_WIN = 8
STATE_WHITE_WIN = 9

LEFT_GPIO = 23
DOWN_GPIO = 22
UP_GPIO = 27
RIGHT_GPIO = 17
ENTER_GPIO = 24
LED_GPIO = 25
